"""Add column last_name to User model

Revision ID: 3291024d8243
Revises: 
Create Date: 2025-09-04 16:04:50.203097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3291024d8243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
