"""4

Revision ID: 9b03c0454ff3
Revises: 0aba66dc91b4
Create Date: 2025-12-11 08:30:48.430820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b03c0454ff3'
down_revision = '0aba66dc91b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
