"""two

Revision ID: d29502eb5a00
Revises: 3291024d8243
Create Date: 2025-09-04 16:06:10.437190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd29502eb5a00'
down_revision = '3291024d8243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
